import type { DashboardMetric } from "./dashboard-definitions";

export interface MetricSample {
  metricId: DashboardMetric["id"];
  currentValue: string;
  deltaLabel: string;
  trend: "up" | "down" | "flat";
  status: "bullish" | "bearish" | "neutral";
  series: number[];
  sourceLabel: string;
}

export const METRIC_SAMPLES: MetricSample[] = [
  {
    metricId: "ssr",
    currentValue: "8.42",
    deltaLabel: "Stablecoin market caps still supportive",
    trend: "down",
    status: "bullish",
    series: [60, 59, 58, 56, 54, 52, 49, 47, 45, 43, 42, 40],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "fear-and-greed",
    currentValue: "41",
    deltaLabel: "Sentiment still below greed",
    trend: "up",
    status: "neutral",
    series: [28, 29, 31, 32, 33, 35, 36, 37, 38, 40, 41, 41],
    sourceLabel: "Alternative.me",
  },
  {
    metricId: "funding-rate",
    currentValue: "0.012%",
    deltaLabel: "Positive, but not overheated",
    trend: "up",
    status: "neutral",
    series: [32, 33, 35, 34, 36, 37, 38, 39, 40, 41, 43, 44],
    sourceLabel: "Venue basket",
  },
  {
    metricId: "open-interest",
    currentValue: "84.1K BTC",
    deltaLabel: "Leverage participation firming",
    trend: "up",
    status: "neutral",
    series: [34, 35, 36, 37, 39, 41, 43, 45, 47, 49, 50, 52],
    sourceLabel: "Binance API + local history",
  },
  {
    metricId: "adjusted-transfer-volume",
    currentValue: "$10.9B",
    deltaLabel: "Settlement demand improving",
    trend: "up",
    status: "neutral",
    series: [30, 31, 29, 33, 36, 35, 39, 41, 43, 44, 46, 47],
    sourceLabel: "Blockchain.com",
  },
  {
    metricId: "mvrv",
    currentValue: "1.91",
    deltaLabel: "Above neutral, below prior heat",
    trend: "up",
    status: "neutral",
    series: [26, 28, 29, 31, 33, 35, 37, 39, 41, 42, 43, 44],
    sourceLabel: "Blockchain.com",
  },
  {
    metricId: "puell-multiple",
    currentValue: "1.08",
    deltaLabel: "Miner stress contained",
    trend: "up",
    status: "neutral",
    series: [28, 29, 30, 31, 32, 33, 35, 37, 39, 40, 41, 42],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "pi-cycle-top",
    currentValue: "27.3%",
    deltaLabel: "Still below the classic trigger",
    trend: "down",
    status: "neutral",
    series: [48, 47, 46, 44, 42, 40, 38, 35, 33, 31, 29, 27],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "mayer-multiple",
    currentValue: "1.17",
    deltaLabel: "Spot remains above the 200DMA",
    trend: "up",
    status: "bullish",
    series: [34, 35, 36, 37, 39, 40, 42, 44, 46, 48, 49, 50],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "2-year-ma-multiplier",
    currentValue: "79.4%",
    deltaLabel: "Large buffer below the hot band",
    trend: "up",
    status: "bullish",
    series: [68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "power-law",
    currentValue: "0.96x",
    deltaLabel: "Spot near the fitted long-run midline",
    trend: "up",
    status: "neutral",
    series: [37, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49],
    sourceLabel: "Local model",
  },
  {
    metricId: "stock-to-flow",
    currentValue: "119.2",
    deltaLabel: "Scarcity model still rising after the halving",
    trend: "up",
    status: "bullish",
    series: [25, 26, 28, 29, 30, 31, 33, 35, 37, 39, 40, 42],
    sourceLabel: "Local model",
  },
  {
    metricId: "active-supply",
    currentValue: "2.46%",
    deltaLabel: "More supply participating on-chain",
    trend: "up",
    status: "neutral",
    series: [26, 27, 28, 29, 31, 33, 34, 35, 36, 37, 38, 40],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "active-addresses",
    currentValue: "914K",
    deltaLabel: "Participation still broad",
    trend: "up",
    status: "bullish",
    series: [31, 32, 34, 35, 36, 38, 39, 40, 42, 43, 45, 46],
    sourceLabel: "Blockchain.com",
  },
  {
    metricId: "hashrate",
    currentValue: "712 EH/s",
    deltaLabel: "Network security near highs",
    trend: "up",
    status: "bullish",
    series: [33, 34, 35, 36, 38, 40, 42, 44, 46, 48, 49, 51],
    sourceLabel: "Blockchain.com",
  },
  {
    metricId: "difficulty",
    currentValue: "91.8T",
    deltaLabel: "Next adjustment slightly positive",
    trend: "up",
    status: "bullish",
    series: [28, 29, 30, 31, 33, 34, 36, 38, 40, 42, 43, 45],
    sourceLabel: "Blockchain.com + mempool.space",
  },
  {
    metricId: "hash-ribbon",
    currentValue: "1.03",
    deltaLabel: "Miner recovery still intact",
    trend: "up",
    status: "bullish",
    series: [22, 23, 24, 25, 27, 29, 31, 34, 36, 38, 40, 42],
    sourceLabel: "Blockchain.com derived",
  },
  {
    metricId: "nvt-signal",
    currentValue: "74.2",
    deltaLabel: "Valuation still supported by activity",
    trend: "down",
    status: "bullish",
    series: [57, 55, 54, 53, 51, 49, 47, 46, 45, 43, 42, 40],
    sourceLabel: "Blockchain.com",
  },
  {
    metricId: "dxy",
    currentValue: "103.4",
    deltaLabel: "Dollar still range-bound",
    trend: "down",
    status: "bullish",
    series: [56, 55, 54, 53, 52, 51, 50, 49, 49, 48, 47, 46],
    sourceLabel: "FRED",
  },
  {
    metricId: "10y-real-yield",
    currentValue: "1.81%",
    deltaLabel: "Real-rate pressure easing slightly",
    trend: "down",
    status: "bullish",
    series: [58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47],
    sourceLabel: "FRED",
  },
  {
    metricId: "fed-balance-sheet",
    currentValue: "$6.9T",
    deltaLabel: "Balance sheet broadly stable",
    trend: "flat",
    status: "neutral",
    series: [40, 40, 40, 40, 41, 41, 41, 41, 42, 42, 42, 42],
    sourceLabel: "FRED",
  },
  {
    metricId: "on-rrp",
    currentValue: "$281B",
    deltaLabel: "Cash parking continues to drain lower",
    trend: "down",
    status: "bullish",
    series: [62, 60, 58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
    sourceLabel: "FRED",
  },
];

const METRIC_SAMPLES_BY_ID = Object.fromEntries(METRIC_SAMPLES.map((sample) => [sample.metricId, sample]));

export function getMetricSample(metricId: DashboardMetric["id"]) {
  return METRIC_SAMPLES_BY_ID[metricId];
}
